server:
  port: 80
  context-path: /
  tomcat:
    uri-encoding: UTF-8
spring:
  http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
    content-type: text/html
  jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/iotsystem
      username: root
      password: root